In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv("../data/raw/temperature_observations_colombia.csv")  # default sep=","
df.columns = df.columns.str.strip()

df.head()

,codigoestacion,codigosensor,fechaobservacion,valorobservado,nombreestacion,departamento,municipio,zonahidrografica,latitud,longitud,descripcionsensor,unidadmedida
0,16025501,68,2016-09-20T04:15:00.000,16.10000,CUCUTILLA - AUT,NORTE DE SANTANDER,CUCUTILLA,CATATUMBO,7.519456,-72.797903,Temp Aire 2 m,°C
1,24015503,68,2018-05-05T18:40:00.000,15.43093,CONFINES - AUT,SANTANDER,CONFINES,SOGAMOSO,6.373028,-73.207608,Temp Aire 2 m,°C
2,21202220,68,2013-12-14T08:00:00.000,16.70000,PARAISO - FOPAE,BOGOTA D.C.,"BOGOTA, D.C",ALTO MAGDALENA,4.617000,-74.050000,Temp Aire 2 m,°C
3,23065503,68,2017-07-04T09:50:00.000,22.60089,EL MIRADOR - AUT,CUNDINAMARCA,SASAIMA,MEDIO MAGDALENA,4.950000,-74.400000,Temp Aire 2 m,°C
4,15065040,68,2018-01-26T12:00:00.000,31.40000,LA PAULINA - AUT,LA GUAJIRA,FONSECA,CARIBE - GUAJIRA,10.898139,-72.828472,Temp Aire 2 m,°C

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   codigoestacion     50000 non-null  int64
 1   codigosensor       50000 non-null  int64
 2   fechaobservacion   50000 non-null  object
 3   valorobservado     50000 non-null  float64
 4   nombreestacion     50000 non-null  object
 5   departamento       50000 non-null  object
 6   municipio          50000 non-null  object
 7   zonahidrografica   50000 non-null  object
 8   latitud            50000 non-null  float64
 9   longitud           50000 non-null  float64
 10  descripcionsensor  50000 non-null  object
 11  unidadmedida       50000 non-null  object
dtypes: float64(3), int64(2), object(7)
memory usage: 4.6+ MB

In [10]:
# Verificacion de nulos
df.isnull().sum()

codigoestacion       0
codigosensor         0
fechaobservacion     0
valorobservado       0
nombreestacion       0
departamento         0
municipio            0
zonahidrografica     0
latitud              0
longitud             0
descripcionsensor    0
unidadmedida         0
dtype: int64

In [11]:
# Revision de duplicados
grain = ["codigoestacion", "codigosensor", "fechaobservacion"]

df.duplicated(subset=grain).sum()

np.int64(0)

In [12]:
df[df.duplicated(subset=grain, keep=False)]

Empty DataFrame
Columns: [codigoestacion, codigosensor, fechaobservacion, valorobservado, nombreestacion, departamento, municipio, zonahidrografica, latitud, longitud, descripcionsensor, unidadmedida]
Index: []

In [13]:
# validacion de tipos
df.dtypes

codigoestacion         int64
codigosensor           int64
fechaobservacion      object
valorobservado       float64
nombreestacion        object
departamento          object
municipio             object
zonahidrografica      object
latitud              float64
longitud             float64
descripcionsensor     object
unidadmedida          object
dtype: object

In [14]:
df["valorobservado"].describe()

count    50000.000000
mean        18.660062
std          6.388992
min          0.000000
25%         15.100000
50%         18.500000
75%         22.828557
max         50.000000
Name: valorobservado, dtype: float64

In [15]:
# Revision de formatos inconsistentes
df["unidadmedida"].unique()

array(['°C'], dtype=object)

In [16]:
df["departamento"].unique()[:10]

array(['NORTE DE SANTANDER', 'SANTANDER', 'BOGOTA D.C.', 'CUNDINAMARCA',
       'LA GUAJIRA', 'ANTIOQUIA', 'CALDAS', 'HUILA', 'CORDOBA', 'CAUCA'],
      dtype=object)

In [17]:
df["municipio"].unique()[:10]

array(['CUCUTILLA', 'CONFINES', 'BOGOTA, D.C', 'SASAIMA', 'FONSECA',
       'SANTA BÁRBARA', 'SUPIA', 'TELLO', 'MONTERÍA', 'LA SIERRA'],
      dtype=object)

In [18]:
# Verificacion de fechas 
df["fechaobservacion"] = pd.to_datetime(df["fechaobservacion"], errors="coerce")
df["fechaobservacion"].isnull().sum()

np.int64(0)

In [19]:
# Verificacion de rango geografico
df["latitud"].describe()

count    50000.000000
mean         5.004974
std          2.052197
min         -4.194000
25%          4.343000
50%          4.718611
75%          5.625831
max         15.797000
Name: latitud, dtype: float64

In [20]:
df["longitud"].describe()

count    50000.000000
mean       -74.880448
std          1.871863
min        -81.731000
25%        -75.793333
50%        -75.003136
75%        -74.072000
max          0.000000
Name: longitud, dtype: float64

In [21]:
df[df["longitud"] == 0]

,codigoestacion,codigosensor,fechaobservacion,valorobservado,nombreestacion,departamento,municipio,zonahidrografica,latitud,longitud,descripcionsensor,unidadmedida
1074,24037620,68,2013-11-26 05:00:00,12.8,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
3394,24037620,68,2014-08-02 02:00:00,6.4,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
3760,24037620,68,2014-07-12 18:00:00,11.0,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
4573,24037620,68,2014-03-05 08:00:00,9.1,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
7490,24037620,68,2014-05-17 07:00:00,6.1,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
8312,88112901,68,2018-02-02 07:20:00,21.1,ECI JULIO GARAVITO EST. EN PRUEBAS,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
11245,88112901,68,2017-04-18 01:36:00,22.6,ECI JULIO GARAVITO EST. EN PRUEBAS,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
14288,88112901,68,2017-03-27 12:20:00,19.1,ECI JULIO GARAVITO EST. EN PRUEBAS,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
15786,24037620,68,2014-06-22 03:00:00,7.4,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
17900,88112901,68,2018-02-11 10:35:00,23.5,ECI JULIO GARAVITO EST. EN PRUEBAS,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
21139,24037620,68,2014-05-07 22:00:00,13.9,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
22184,24037620,68,2014-04-07 01:00:00,8.1,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
25569,24037620,68,2014-06-18 18:00:00,15.9,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
30430,88112901,68,2017-04-19 08:32:00,21.6,ECI JULIO GARAVITO EST. EN PRUEBAS,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C
35260,24037620,68,2014-05-14 22:00:00,12.1,PTE CALVARIO - SIN TX SATELITAL,<nil>,<nil>,<nil>,0.0,0.0,Temp Aire 2 m,°C

In [24]:
(df == "<nil>").sum()

codigoestacion        0
codigosensor          0
fechaobservacion      0
valorobservado        0
nombreestacion        0
departamento         15
municipio            15
zonahidrografica     89
latitud               0
longitud              0
descripcionsensor     0
unidadmedida          0
dtype: int64